"""
Input processing module for process data.

This module processes manufacturing process data to generate input features
that correspond to the targets generated by the target_processing module.
"""

from .filter_by_hsic import filter_by_hsic
from .generate_tabular_dataset import generate_tabular_dataset

__all__ = ['filter_by_hsic', 'generate_tabular_dataset']
